/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppTachesRouteImport } from './routes/app.taches'
import { Route as AppRisquesRouteImport } from './routes/app.risques'
import { Route as AppRessourcesRouteImport } from './routes/app.ressources'
import { Route as AppProjetsRouteImport } from './routes/app.projets'
import { Route as AppIaRouteImport } from './routes/app.ia'
import { Route as AppFinanceRouteImport } from './routes/app.finance'
import { Route as AppDocumentsRouteImport } from './routes/app.documents'

const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppTachesRoute = AppTachesRouteImport.update({
  id: '/taches',
  path: '/taches',
  getParentRoute: () => AppRoute,
} as any)
const AppRisquesRoute = AppRisquesRouteImport.update({
  id: '/risques',
  path: '/risques',
  getParentRoute: () => AppRoute,
} as any)
const AppRessourcesRoute = AppRessourcesRouteImport.update({
  id: '/ressources',
  path: '/ressources',
  getParentRoute: () => AppRoute,
} as any)
const AppProjetsRoute = AppProjetsRouteImport.update({
  id: '/projets',
  path: '/projets',
  getParentRoute: () => AppRoute,
} as any)
const AppIaRoute = AppIaRouteImport.update({
  id: '/ia',
  path: '/ia',
  getParentRoute: () => AppRoute,
} as any)
const AppFinanceRoute = AppFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => AppRoute,
} as any)
const AppDocumentsRoute = AppDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/documents': typeof AppDocumentsRoute
  '/app/finance': typeof AppFinanceRoute
  '/app/ia': typeof AppIaRoute
  '/app/projets': typeof AppProjetsRoute
  '/app/ressources': typeof AppRessourcesRoute
  '/app/risques': typeof AppRisquesRoute
  '/app/taches': typeof AppTachesRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app/documents': typeof AppDocumentsRoute
  '/app/finance': typeof AppFinanceRoute
  '/app/ia': typeof AppIaRoute
  '/app/projets': typeof AppProjetsRoute
  '/app/ressources': typeof AppRessourcesRoute
  '/app/risques': typeof AppRisquesRoute
  '/app/taches': typeof AppTachesRoute
  '/app': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/documents': typeof AppDocumentsRoute
  '/app/finance': typeof AppFinanceRoute
  '/app/ia': typeof AppIaRoute
  '/app/projets': typeof AppProjetsRoute
  '/app/ressources': typeof AppRessourcesRoute
  '/app/risques': typeof AppRisquesRoute
  '/app/taches': typeof AppTachesRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/app/documents'
    | '/app/finance'
    | '/app/ia'
    | '/app/projets'
    | '/app/ressources'
    | '/app/risques'
    | '/app/taches'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app/documents'
    | '/app/finance'
    | '/app/ia'
    | '/app/projets'
    | '/app/ressources'
    | '/app/risques'
    | '/app/taches'
    | '/app'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/app/documents'
    | '/app/finance'
    | '/app/ia'
    | '/app/projets'
    | '/app/ressources'
    | '/app/risques'
    | '/app/taches'
    | '/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/taches': {
      id: '/app/taches'
      path: '/taches'
      fullPath: '/app/taches'
      preLoaderRoute: typeof AppTachesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/risques': {
      id: '/app/risques'
      path: '/risques'
      fullPath: '/app/risques'
      preLoaderRoute: typeof AppRisquesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/ressources': {
      id: '/app/ressources'
      path: '/ressources'
      fullPath: '/app/ressources'
      preLoaderRoute: typeof AppRessourcesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/projets': {
      id: '/app/projets'
      path: '/projets'
      fullPath: '/app/projets'
      preLoaderRoute: typeof AppProjetsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/ia': {
      id: '/app/ia'
      path: '/ia'
      fullPath: '/app/ia'
      preLoaderRoute: typeof AppIaRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/finance': {
      id: '/app/finance'
      path: '/finance'
      fullPath: '/app/finance'
      preLoaderRoute: typeof AppFinanceRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/documents': {
      id: '/app/documents'
      path: '/documents'
      fullPath: '/app/documents'
      preLoaderRoute: typeof AppDocumentsRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppDocumentsRoute: typeof AppDocumentsRoute
  AppFinanceRoute: typeof AppFinanceRoute
  AppIaRoute: typeof AppIaRoute
  AppProjetsRoute: typeof AppProjetsRoute
  AppRessourcesRoute: typeof AppRessourcesRoute
  AppRisquesRoute: typeof AppRisquesRoute
  AppTachesRoute: typeof AppTachesRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDocumentsRoute: AppDocumentsRoute,
  AppFinanceRoute: AppFinanceRoute,
  AppIaRoute: AppIaRoute,
  AppProjetsRoute: AppProjetsRoute,
  AppRessourcesRoute: AppRessourcesRoute,
  AppRisquesRoute: AppRisquesRoute,
  AppTachesRoute: AppTachesRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
